DEV-7353-Fixed dropdown component in UI library
pidedirecto/pidedirectoui pull request #27
Opened 2024-05-03 23:35 UTC by SoyTanMax

### Before sending PR for review confirm that
- [ ] self review of PR is made and conventions are checked (check "Files changed" tab in PR) 
- [ ] all merge conflict are solved
- [ ] CICD checks passes

2024-05-04 00:20 UTC, oscarmg11 requested changes

2024-05-04 00:20 UTC, oscarmg11 commented on src/components/DropDown.tsx
> +            {isOpen && (
React portal is needed, why did u remove it? What are u fixing here?

2024-05-04 01:13 UTC, SoyTanMax commented on src/components/DropDown.tsx
> +            {isOpen && (
I thought it was the reason why the styles didn't work, but the only thing wrong was the document.body line. The position of the list was fixed and I changed it to absolute so it doesn't stay in the same position even though you scroll and it can be handled with css, no js needed :)

2024-05-07 17:59 UTC, oscarmg11 approved these changes

2024-05-07 18:47 UTC, oscarmg11 requested changes

2024-05-07 18:47 UTC, oscarmg11 commented on src/components/DialogContent.tsx
> + * @flow
Remove flow annotation

2024-05-07 18:47 UTC, oscarmg11 commented on src/components/DialogContent.tsx
> +export function DialogContent({ children, className }: DialogContentProps): React.ReactElement {
To add a component you have to do more several things besides than creating the styles and the `d.ts` file

1. Export it from the `src/components/main` file, every files that should be used outside the library should be exported through some og these `main` files, `src/icons/main` for icons, `src/form/main` for form components, etc.

2. Export the type from `src/index.d.ts`, in the previous code you exported the actual code, with this you export the types code, so ts can know what props and what component is this.

3. Add documentation, for this step you have to create 2 files, a `story` file inside `src/stories` and a mdx file, this file is the actual written documentation, if this `DialogContent` component it supossed to be used at some point then document it cause if you don't do it, anyone will know that this component exists and what this is used for

2024-05-13 16:00 UTC, oscarmg11 approved these changes

2024-05-14 20:30 UTC, closed without merging