chore: Add Loader component to App.tsx
pidedirecto/pidedirectoui pull request #39
Opened 2024-05-29 18:41 UTC by marcosstevens2012

### Before sending PR for review confirm that
- [ ] self review of PR is made and conventions are checked (check "Files changed" tab in PR) 
- [ ] all merge conflict are solved
- [ ] CICD checks passes

2024-05-30 15:49 UTC, oscarmg11 commented on src/App.tsx
> +            <Loader isLoading={false}> </Loader>
It does not have an isLoading prop, no?

2024-05-30 15:51 UTC, oscarmg11 commented on src/styles/loader.module.css
> +p {
Don't query p elements in general, just change the p inside .loaderContainer, also the font family, why arial? we use popins use it, we already have a Text component, it is not useful here? Also the color, i'm pretty sure it should not be #333, cause it is not one of the defined colors we have

2024-05-31 17:28 UTC, oscarmg11 requested changes

2024-05-31 17:28 UTC, oscarmg11 commented on src/components/main.ts
> +export * from 'src/components/SlidingDots';
Do we need to expose the component SlidingDots to the consumer of the library? I don't think so, no? We just need the loader

2024-05-31 17:28 UTC, oscarmg11 commented on src/components/Loader.tsx
> +type Props = Omit<HTMLProps<HTMLSpanElement>, 'className'> & {
Remove this props type, is not needed, cause you don't use the whole span attributes, you just use the loading prop, better use `LoaderProps` from the `Loader.d.ts` file

2024-06-01 16:44 UTC, marcosstevens2012 commented on src/components/main.ts
> +export * from 'src/components/SlidingDots';
the sliding dots replace the MIUI circular progress, you don't always need the loader, sometimes only the dots

2024-06-26 15:43 UTC, oscarmg11 requested changes

2024-06-26 15:43 UTC, oscarmg11 commented on src/components/SlidingDots.tsx
> +export function SlidingDots(): React.ReactElement {
I think this component is not needed just put these div and span inside de `Loader` component

2024-06-26 15:43 UTC, oscarmg11 commented on src/components/Loader.tsx
> +export function Loader({ loading, loadingText }: LoaderProps): React.ReactElement | null {
Just `text` instead of `loadingText` is better

2024-06-26 16:25 UTC, merged